# -*- coding: utf-8 -*-
"""exploratory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MqLv_qi_-8khzR_-6k-aZwnHs2wgEjx6
"""

##By Wyatt Van Dyke
##importing stuff
!pip install CurrencyConverter
import pandas as pd
import numpy as np
from currency_converter import CurrencyConverter
import matplotlib.pyplot as plt
import seaborn as sns
import io
from google.colab import drive
drive.mount('/content/drive')

pd.options.display.max_rows = 100  # default is 60 rows

#I used Sublime Text to fix the file and encode it in UTF-8
file_path = '/content/drive/My Drive/wfp_market_food_prices.csv'  # Update the path if needed
df_market = pd.read_csv(file_path, encoding='ISO-8859-1')

df_market.shape

df_market.values

df_market.info()

filter_middleeast = df_market[df_market['adm0_name'].isin(['Azerbaijan', 'Jordan', 'Lebanon', 'Syrian Arab Republic', 'Turkey', 'Yemen'])].copy()

filter_middleeast

#no duplicate rows found, that's good
duplicateRows = filter_middleeast[filter_middleeast.duplicated()]
duplicateRows

filter_middleeast.cur_name.unique()

c = CurrencyConverter()
currencies = filter_middleeast.cur_name.unique().tolist()
currencies = dict.fromkeys(currencies, pd.NA)
for key in currencies:
   try:
      currencies[key] = c.convert(1, 'USD', key)
   except:
      pass

filter_middleeast.loc[:,'amount_conv'] = filter_middleeast.apply(lambda x: x.mp_price / currencies[x.cur_name], axis=1 )

filter_middleeast.um_name.unique()

#everything is in retail
filter_middleeast.pt_name.unique()

filter_middleeast.loc[:, ['mp_month', 'mp_year']]

filter_middleeast.mp_commoditysource.unique()

filter_middleeast.cm_name.unique()

#removing currency since all are now USD, please ignore error
filter_middleeast = filter_middleeast.drop(['cur_id', 'cur_name'], axis=1)

#thanks to raghuveer for the rename code
filter_middleeast.rename(columns={
    'adm0_id': 'country_id',
    'adm0_name': 'country_name',
    'adm1_id': 'region_id',
    'adm1_name': 'region_name',
    'mkt_id': 'market_id',
    'cm_id': 'commodity_id',
    'pt_id': 'price_type_id',
    'um_id': 'unit_measure_id',
    'mp_month': 'price_month',
    'mp_year': 'price_year',
    'mp_price': 'price'
}, inplace=True)

filter_middleeast.describe(include='all')

# Group by Country and calculate the mean, median, and standard deviation of mp_price
country_price_summary = filter_middleeast.groupby('country_name')['price'].agg(['mean', 'median', 'std', 'count']).reset_index()
country_price_summary.columns = ['Country Name', 'Mean Price', 'Median Price', 'Std Dev Price', 'Count']
print(country_price_summary,"\n")

# Group by Region
region_price_summary = filter_middleeast.groupby('region_name')['price'].agg(['mean', 'median', 'std', 'count']).reset_index()
region_price_summary.columns = ['Region Name', 'Mean Price', 'Median Price', 'Std Dev Price', 'Count']
print(region_price_summary,"\n")

# Group by Market Name
mkt_price_summary = filter_middleeast.groupby('mkt_name')['price'].agg(['mean', 'median', 'std', 'count']).reset_index()
mkt_price_summary.columns = ['Market Name', 'Mean Price', 'Median Price', 'Std Dev Price', 'Count']
print(mkt_price_summary,"\n")

# Group by Commodity Name
cm_price_summary = filter_middleeast.groupby('cm_name')['price'].agg(['mean', 'median', 'std', 'count']).reset_index()
cm_price_summary.columns = ['Commodity Name', 'Mean Price', 'Median Price', 'Std Dev Price', 'Count']
print(cm_price_summary,"\n")

# Group by Market Type (there's only one, it's retail)
mk_type_price_summary = filter_middleeast.groupby('pt_name')['price'].agg(['mean', 'median', 'std', 'count']).reset_index()
mk_type_price_summary.columns = ['Market Type', 'Mean Price', 'Median Price', 'Std Dev Price', 'Count']
print(mk_type_price_summary,"\n")

# Maximum Median Price by Country
max_country_index = country_price_summary['Median Price'].idxmax()
max_median_price_country = country_price_summary.loc[max_country_index]
print("Maximum Median Price by Country:", max_median_price_country['Country Name'], "with a price of:", max_median_price_country['Median Price'])

# Maximum Median Price by Locality Name
max_region_index = region_price_summary['Median Price'].idxmax()
max_median_price_region = region_price_summary.loc[max_region_index]
print("Maximum Median Price by Region Name:", max_median_price_region['Region Name'], "with a price of:", max_median_price_region['Median Price'])

# Maximum Median Price by Market Name
max_market_index = mkt_price_summary['Median Price'].idxmax()
max_median_price_market = mkt_price_summary.loc[max_market_index]
print("Maximum Median Price by Market Name:", max_median_price_market['Market Name'], "with a price of:", max_median_price_market['Median Price'])

# Maximum Median Price by Commodity Name
max_commodity_index = cm_price_summary['Median Price'].idxmax()
max_median_price_commodity = cm_price_summary.loc[max_commodity_index]
print("Maximum Median Price by Commodity Name:", max_median_price_commodity['Commodity Name'], "with a price of:", max_median_price_commodity['Median Price'])

# Maximum Median Price by Market Type Name
max_market_type_index = mk_type_price_summary['Median Price'].idxmax()
max_median_price_market_type = mk_type_price_summary.loc[max_market_type_index]
print("Maximum Median Price by Market Type:", max_median_price_market_type['Market Type'], "with a price of:", max_median_price_market_type['Median Price'])

# Create a function to plot median prices for a given filter and title
def plot_median_price(data, title):
    median_data = data.groupby('price_year')['price'].median().reset_index()

    plt.figure(figsize=(10, 6))
    plt.plot(median_data['price_year'], median_data['price'], marker='o', linestyle='-')
    plt.title(title)
    plt.xlabel('Year')
    plt.ylabel('Median Price')
    plt.xticks(rotation=45)
    plt.grid()
    plt.tight_layout()
    plt.show()

# Filter and plot for Lebanon
lebanon_data = filter_middleeast[filter_middleeast['country_name'] == 'Lebanon']
plot_median_price(lebanon_data, 'Median Price Over Time - Lebanon')

# Filter and plot for Beirut
beirut_data = filter_middleeast[filter_middleeast['region_name'] == 'Beirut']
plot_median_price(beirut_data, 'Median Price Over Time - Beirut')

# Filter and plot for Baabda
baabda_data = filter_middleeast[filter_middleeast['mkt_name'] == 'Baabda']
plot_median_price(baabda_data, 'Median Price Over Time - Baabda')

# Filter and plot for Sheep (2-year old male)
sheep_data = filter_middleeast[filter_middleeast['cm_name'] == 'Livestock (sheep, two-year-old male)']
plot_median_price(sheep_data, 'Median Price Over Time - Sheep (2-year old male)')

# Filter and plot for Retail
retail_data = filter_middleeast[filter_middleeast['pt_name'] == 'Retail']
plot_median_price(retail_data, 'Median Price Over Time - Retail')

filter_middleeast

me_numeric = filter_middleeast[["country_id", "region_id", "market_id", "commodity_id", "unit_measure_id", "price_month", "price_year", "price"]]

me_numeric.corr()

dataplot = sns.heatmap(me_numeric.corr(numeric_only=True), cmap="YlGnBu", annot=True)
plt.show()

#thanks pranav
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

# List of individual features to test against 'price'
features = ["country_id", "region_id", "market_id", "commodity_id", "unit_measure_id"]

# Initialize the LinearRegression model
model = LinearRegression()

# Loop through each feature
for feature in features:
    X_single = me_numeric[[feature]]  # Select a single feature (reshape to 2D)
    y = me_numeric['price']  # Target variable

    # Split the data for training and testing (70% training, 30% testing)
    X_train, X_test, y_train, y_test = train_test_split(X_single, y, test_size=0.3, random_state=42)

    # Fit the linear regression model for the current feature
    model.fit(X_train, y_train)

    # Predict on the test set
    y_pred = model.predict(X_test)

    # Calculate the R-squared value
    r2 = r2_score(y_test, y_pred)

    # Plot the actual vs predicted values
    plt.figure(figsize=(8, 6))
    sns.scatterplot(x=X_test[feature], y=y_test, label='Actual', color='blue')
    sns.lineplot(x=X_test[feature], y=y_pred, label='Regression Line', color='red')

    # Add title and labels
    plt.title(f'Single-Variable Linear Regression for {feature}\nR-squared: {r2:.4f}')
    plt.xlabel(feature)
    plt.ylabel('price')

    # Show plot
    plt.legend()
    plt.show()

"""Not a very effective measure since we're using categorical variables in place of numeric variables, like Pranav said. Oopsie."""

from scipy import stats
import statsmodels.api as sm
from statsmodels.formula.api import ols

def perform_tests(filter_middleeast, categorical_var):
    # Perform Shapiro-Wilk test for normality
    shapiro_test = stats.shapiro(filter_middleeast['price'])
    print(f"Shapiro-Wilk Test for {categorical_var}: Statistic={shapiro_test.statistic}, p-value={shapiro_test.pvalue}")

    # Check if p-value is less than significance level (e.g., 0.05)
    if shapiro_test.pvalue < 0.05:
        print(f"Normality does not hold for {categorical_var}. Proceeding with Kruskal-Wallis test.")

        # Perform Kruskal-Wallis test
        kruskal_test = stats.kruskal(*(filter_middleeast[filter_middleeast[categorical_var] == cat]['price']
                                        for cat in filter_middleeast[categorical_var].unique()))
        print(f"Kruskal-Wallis Test for {categorical_var}: Statistic={kruskal_test.statistic}, p-value={kruskal_test.pvalue}")
    else:
        print(f"Normality holds for {categorical_var}. Proceeding with ANOVA.")

        # Perform ANOVA
        model = ols(f'mp_price ~ C({categorical_var})', data=filter_middleeast).fit()
        anova_results = sm.stats.anova_lm(model, typ=2)
        print(anova_results)

categorical_vars = ['country_name', 'region_name', 'mkt_name', 'cm_name', 'price_year', 'price_month']

for var in categorical_vars:
    perform_tests(filter_middleeast, var)

"""pt_name was throwing up errors so i excluded it

Kruskal-Wallis tests for country_name, mkt_name, cm_name, and price_year show very large statistics that indicate a large impact on price.

NaN result in Kruskal-Wallis test probably means we need to check the variable's data.

price_month doesn't have as big as an impact as the other variables because of its small statistic.

I decided to throw this out and take a different approach. Thanks Raghuveer for the code that works.

# Categorical Analysis, for real this time
"""

filter_middleeast

#Thanks Raghuveer
# Group by country and commodity category to calculate min, max, and average prices
country_price_ranges = filter_middleeast.groupby(['country_name', 'cm_name']).agg({
    'price': ['min', 'max', 'mean']
}).reset_index()
print(country_price_ranges)

from sklearn.preprocessing import PolynomialFeatures, OneHotEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

features = ['country_id', 'region_id', 'market_id', 'commodity_id', 'unit_measure_id', 'price_month', 'price_year']
target = 'price'


# One-hot encode categorical features and scale numerical features
preprocessor = ColumnTransformer(transformers=[
    ('cat', OneHotEncoder(), ['country_id', 'region_id', 'market_id', 'commodity_id']),
    ('num', StandardScaler(), ['price_month', 'price_year'])
])


# Polynomial degree (adjust this as needed)
poly = PolynomialFeatures(degree=2)

# Create a pipeline
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('poly', poly),
    ('regressor', LinearRegression())
])


# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(filter_middleeast[features], filter_middleeast[target], test_size=0.2, random_state=42)

# Fit the model
pipeline.fit(X_train, y_train)

# Predict prices on the test set
y_pred = pipeline.predict(X_test)

# Evaluate the model (example: mean squared error, R-squared score)
from sklearn.metrics import r2_score

mse = (y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared Score: {r2}")

import matplotlib.pyplot as plt
import numpy as np

# Assuming we have fitted the model as shown before

# 1. Predicted vs Actual Price Plot
y_pred = pipeline.predict(X_test)

plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, color='blue', edgecolor='k', alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel('Actual Price')
plt.ylabel('Predicted Price')
plt.title('Predicted vs Actual Price')
plt.show()

# 2. 3D Polynomial Surface Plot (if focusing on two features)
# Let's focus on 'price_year' and 'price_month' for 3D visualization

# Select two features for a simpler 3D plot
X_train_2d = X_train[['price_year', 'price_month']].values
X_test_2d = X_test[['price_year', 'price_month']].values

# Train a polynomial regression model on these two features
pipeline_2d = Pipeline(steps=[
    ('scaler', StandardScaler()),
    ('poly', PolynomialFeatures(degree=2)),
    ('regressor', LinearRegression())
])

pipeline_2d.fit(X_train_2d, y_train)

# Generate a meshgrid for the 3D surface plot
x0_range = np.linspace(X_test_2d[:, 0].min(), X_test_2d[:, 0].max(), 100)
x1_range = np.linspace(X_test_2d[:, 1].min(), X_test_2d[:, 1].max(), 100)
X0, X1 = np.meshgrid(x0_range, x1_range)
X_grid = np.c_[X0.ravel(), X1.ravel()]

# Predict prices for the grid
y_grid_pred = pipeline_2d.predict(X_grid).reshape(X0.shape)

# Plotting in 3D
fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(X0, X1, y_grid_pred, cmap='viridis', alpha=0.8)

# Scatter actual test data points
ax.scatter(X_test_2d[:, 0], X_test_2d[:, 1], y_test, color='r', marker='o')

ax.set_xlabel('Year')
ax.set_ylabel('Month')
ax.set_zlabel('Price')
ax.set_title('3D Polynomial Regression Surface')
plt.show()